### ISSUE TITLE
`rescue in block in dlload': can't load D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/vendor/libui.dll (Fiddle::DLError)

### ISSUE THREAD

**Issue by kematy** [kojix2/LibUI#15]
D:/Ruby25/lib/ruby/2.5.0/fiddle/import.rb:89:in `rescue in block in dlload': can't load D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/vendor/libui.dll (Fiddle::DLError)
	from D:/Ruby25/lib/ruby/2.5.0/fiddle/import.rb:86:in `block in dlload'
	from D:/Ruby25/lib/ruby/2.5.0/fiddle/import.rb:77:in `collect'
	from D:/Ruby25/lib/ruby/2.5.0/fiddle/import.rb:77:in `dlload'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui/ffi.rb:78:in `<module:FFI>'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui/ffi.rb:74:in `<module:LibUI>'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui/ffi.rb:73:in `<top (required)>'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui.rb:28:in `require_relative'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui.rb:28:in `<module:LibUI>'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui.rb:6:in `<top (required)>'
	from D:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'

**Comment by kojix2** [comment]
At first glance, it may be a Fiddle problem.

1. Can you call Fiddle?

```ruby
require 'fiddle'
```

2. If it does, what version of Fiddle do you have?

```ruby
require 'fiddle'
p Fiddle::VERSION
```

The VERSION constant was added recently, so it may not exist. It means that it is prior to 1.0.0.

**Comment by kojix2** [comment]
How did you install Ruby on Windows? 
RubyInstaller?

**Comment by kematy** [comment]
I install ruby with RubyInstaller.
irb(main):001:0> require 'fiddle'
=> false
gem install fiddle
Fetching: fiddle-1.0.8.gem (100%)
Temporarily enhancing PATH for MSYS/MINGW...
Installing required msys2 packages: mingw-w64-i686-libffi
错误：无法打开文件 /var/lib/pacman/local/mingw-w64-i686-gnutls-3.6.13-2/desc: No such file or directory
Building native extensions. This could take a while...

**Comment by kematy** [comment]
in msys2, pacman -Syu   update system
pacman -S mingw-w64-i686-libffi

then in cmd :gem install fiddle
irb(main):001:0> require 'fiddle'
=> false
irb(main):002:0> p Fiddle::VERSION
"1.0.8"
=> "1.0.8"

then

D:/Ruby25/lib/ruby/gems/2.5.0/gems/fiddle-1.0.8/lib/fiddle.rb:67: warning: already initialized constant Fiddle::RTLD_GLOBAL
D:/Ruby25/lib/ruby/2.5.0/fiddle.rb:53: warning: previous definition of RTLD_GLOBAL was here
D:/Ruby25/lib/ruby/gems/2.5.0/gems/fiddle-1.0.8/lib/fiddle.rb:68: warning: already initialized constant Fiddle::RTLD_LAZY
D:/Ruby25/lib/ruby/2.5.0/fiddle.rb:54: warning: previous definition of RTLD_LAZY was here
D:/Ruby25/lib/ruby/gems/2.5.0/gems/fiddle-1.0.8/lib/fiddle.rb:69: warning: already initialized constant Fiddle::RTLD_NOW
D:/Ruby25/lib/ruby/2.5.0/fiddle.rb:55: warning: previous definition of RTLD_NOW was here
D:/Ruby25/lib/ruby/gems/2.5.0/gems/fiddle-1.0.8/lib/fiddle.rb:61:in `initialize': Exec format error (Fiddle::DLError)
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/fiddle-1.0.8/lib/fiddle.rb:61:in `new'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/fiddle-1.0.8/lib/fiddle.rb:61:in `dlopen'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/fiddle-1.0.8/lib/fiddle/import.rb:86:in `block in dlload'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/fiddle-1.0.8/lib/fiddle/import.rb:77:in `collect'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/fiddle-1.0.8/lib/fiddle/import.rb:77:in `dlload'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui/ffi.rb:78:in `<module:FFI>'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui/ffi.rb:74:in `<module:LibUI>'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui/ffi.rb:73:in `<top (required)>'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui.rb:28:in `require_relative'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui.rb:28:in `<module:LibUI>'
	from D:/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/lib/libui.rb:6:in `<top (required)>'
	from D:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from D:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from D:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from D:/ruby-lab/guis/libui.rb:1:in `<main>'

**Comment by kojix2** [comment]
Thanks.

Sorry, It doesn't seem to be a fiddle problem. 
It seems that libui.dll cannot be loaded. LibUI problem.

First, we need to find out if libui.dll exists.

`/Ruby25/lib/ruby/gems/2.5.0/gems/libui-0.0.8/vendor/libui.dll` 

![image](https://user-images.githubusercontent.com/5798442/117246827-41e88c80-ae78-11eb-8b8c-ccb1da99d57f.png)
![image](https://user-images.githubusercontent.com/5798442/117246889-562c8980-ae78-11eb-8338-e64ec79d2fea.png)

Check the file size and make sure the file is not corrupt.
![image](https://user-images.githubusercontent.com/5798442/117247200-d05d0e00-ae78-11eb-879f-41dd5be2d61c.png)


Or check the checksum.
md5sum: `9da0a8556133fbc46c08c956a0ef5746`

**Comment by kematy** [comment]
Only ofr 64 bit Ruby? 
![答复111](https://user-images.githubusercontent.com/45848649/117247734-68ef9000-ae71-11eb-9d2a-e37886ea59a1.jpg)

**Comment by kojix2** [comment]
Only the 64bit version is packed in the Gem. (´-ω-`)
Other versions are distributed on the libui site.
If you replace it, it might work.

https://github.com/andlabs/libui/releases/tag/alpha4.1

**Comment by kematy** [comment]
Thank you

**Comment by kojix2** [comment]
Now I can reproduce the issue. 

| Ruby | libui.dll| work? |
|--------|-----------|---|
| Ruby+Devkit 2.5.9-1 (x86) | libui-alpha4.1-windows-amd64-shared.zip |  Not work |
| Ruby+Devkit 2.5.9-1 (x86) | libui-alpha4.1-windows-386-shared.zip |  OK |

Thank you for your report. 
If there are no further problems, please close it.

**Comment by kojix2** [comment]
Updates
Added a task to the Rakefile to download the 32-bit libui shared library.

```
rake vendor:all_x64      # Download libui.so, libui.dylib, and libui.dll to...
rake vendor:linux_x64    # Download libui.so for Linux to vendor directory
rake vendor:linux_x86    # Download libui.so for Linux to vendor directory
rake vendor:mac_x64      # Download libui.dylib for Mac to vendor directory
rake vendor:windows_x64  # Download libui.dll for Windows to vendor directory
rake vendor:windows_x86  # Download libui.dll for Windows to vendor directory
```

So, you can install it as follows

```sh
rake vendor:windows_x86
rake install
```

**Comment by rubyFeedback** [comment]
Oddly enough I re-installed the Win10 laptop and I ran into the exact same issue.

The strange thing is that prior to the re-installation, that issue did not happen.

Right now I am a bit confused how this error shows up. I don't recall what I did
different prior to the reinstall; always installed via "gem install libui".

**Comment by kojix2** [comment]
@rubyFeedback 
Please tell us a little more about your environment.
Did you use RubyInstaller to install Ruby, and is Ruby really a 64-bit version?
Obviously using a 32bit version of Ruby will cause problems, but other causes are less clear and need to be investigated.

**Comment by kojix2** [comment]
One way to tell 64bit Ruby from 32bit Ruby is to use
`ruby -e "puts 1.size"`

If it is 4, it is 32-bit, and if it is 8, it is 64-bit.
