### ISSUE TITLE
Just some feedback on the ORCA - worked for me on the first (actually second) try.

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/LibUI#18]
Building an .exe via ORCA worked on the second try. First one I
did not know an .exe would be built, so I interrupted. But then it
continued and eventually I realized that orca was trying to put
it all into an .exe.

The command I used was:

    ocra examples/control_gallery.rb --dll ruby_builtin_dlls/libssp-0.dll --dll ruby_builtin_dlls/libgmp-10.dll --dll ruby_builtin_dlls/libffi-7.dll --gem-all=fiddle --output control_gallery.exe

This is just some feedback. It's simpler than any of the alternatives for windows, be it fxruby, 
gtk or anything.

I understand that libui possibly isn't trivial to put into a OOP variant (tons of FiddlePointers
which I assume can not be easily modified by pure ruby as such), but as far as simplicity is
concerned, libui beats the other toolkits.

Now I am going the long road to port my ruby-gtk3 applications, if I need them to run on
windows. :) (I failed compiling on windows; got gtk-related missing symbols and then 
gave up on it. It's more interesting to add functionality e. g. to libui knowing where it
works, rather than spend more hours in gtk-on-windows when I keep hitting my head
against the wall with it ...)

**Comment by kojix2** [comment]
Hi @rubyFeedback 
Thank you for your report.

I am glad you were able to create the exe on Windows.

The LibUI source code is very simple and is just a wrapper for LibuUI. I am getting busier and busier, and my time for OSS activities is getting shorter and shorter. LibUI is a free software, so feel free to fork it and improve it, or wrap LibUI to make even more useful tool.

What I would like to suggest is to upload the source code to a repository such as Github. You don't have to publish all of your code. I don't know what you are trying to create, but if you upload the source code, it will make it easier for others to see. You don't have to show us all the code, just the parts you don't care about. This will make it easier for others to understand what you want and support your project. The code will tell your story.

Please take care of yourself.
