### ISSUE TITLE
libui examples - see https://ring-lang.github.io/doc1.14/libui.html in particular for the "Text Drawing" example

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/LibUI#21]
Heya,

See this website: https://ring-lang.github.io/doc1.14/libui.html

(I did not know about the ring language, but for the purpose of this thread
I am only interested in the examples.)

The "Text Drawing" example shows how to use coloured text and what not.

I am trying to include this so that I can port my ruby-gtk3 widgets set into
libui, on windows. So having colours, and so forth would be great.

I tried to adapt it:

    string = UI.new_attributed_string
    attribute = UI.new_color_attribute(0.75, 0.25, 0.5, 0.75)
    UI.attributed_string_append_unattributed('text color', attribute)

But I don't quite understand the API. I did however find out that I can
modify Fiddle::Pointer on an ad-hoc basis which is funny. I simply
added .add() and .set_text() ... always feeling that I am on the
risk of segfaulting EVERYTHING. And indeed I do! But I digress. :D

Would it be possible that ruby-LibUI could show a small Text Drawing
example? All examples may not have to be shown, I just wonder
about the API. 

I understand that we first have to define the attribute and then somehow
tie this to the string, but I have no idea how to add this to the main 
window then. So any example in this regard, even if only small, just
to show e. g. red coloured text, would be super-useful. Thanks for
reading!

**Comment by kojix2** [comment]
#20
I've added a sample of draw text.
But I added it in a hurry, so there might be a lot of mistakes.

If you find any mistakes, please send me a pull request!
(This is important!)
