### ISSUE TITLE
callback for UI.timer

### ISSUE THREAD

**Issue by kojix2** [kojix2/LibUI#33]
You can't write this way.

```ruby
UI.timer(1000) do
  puts "hello"
  0
end
```

```
can't modify frozen Integer: 1000 (FrozenError)
```

Cannot add callbacks as instance variables to 1000. (This is necessary to avoid garbage collection.)

You can write it this way.

```ruby
c = Fiddle::Closure::BlockCaller.new(4, [0]) { puts "hello"; 0}
UI.timer(1000, c)
```

However, the first way of writing is better.

**Comment by kojix2** [comment]
An easy way to solve this problem is to override UI.timer. However, before you do that, you might want to check other callbacks used in libui. There may be other functions that cause the same problem.

**Comment by AndyObtiva** [comment]
I just added support for timer and queue_main block syntax to Glimmer DSL for LibUI today (0.2.0)

Here are examples using it:

https://github.com/AndyObtiva/glimmer-dsl-libui/#timer

https://github.com/AndyObtiva/glimmer-dsl-libui/#color-the-circles

The implementation includes some extra convenience options like specifying repeat option as a finite integer or disabling repetition after one run (currently at the bottom of this file):

https://github.com/AndyObtiva/glimmer-dsl-libui/blob/master/lib/glimmer/libui.rb

So, your implementation in LibUI is more than good enough at the binding layer to enable Glimmer’s code at the higher DSL layer. I don’t think you have to worry about it.

**Comment by kojix2** [comment]
Amazing!
You work so fast, I can't keep up with you at all.

**Comment by kojix2** [comment]
* uiQueueMain
* uiOnShouldQuit

**Comment by kojix2** [comment]
Maybe I could have solved this issue, but I haven't tested it enough, so I'll wait and see.

**Comment by AndyObtiva** [comment]
Given the [Layered Architecture](https://www.oreilly.com/library/view/software-architecture-patterns/9781491971437/ch01.html) of [Glimmer DSL for LibUI](https://github.com/AndyObtiva/glimmer-dsl-libui), I think we have the following layers from top to bottom, and each is performing its function sufficiently, so I wouldn't worry:
- DSL layer for desktop application developers to build GUI with the simplest declarative hierarchical object-oriented syntax possible.
- Binding layer for mapping C functions to Ruby to make LibUI available in the Ruby programming language.
- Implementation layer for implementing libui in C on top of each operating system's windowing system.
- Windowing layer, which varies per operating system (Cocoa on Mac, Win32 on Windows, and GTK on Linux).
- CPU architecture layer, which varier per CPU hardware (e.g. x86_64 vs Aarch64).
