### ISSUE TITLE
Addition of another example? Basic colour table - see Andy's example in glimmer-libui-dsl

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/LibUI#40]
Heya kojix2 (and Andy and everyone else reading this),

Andy added TONS of examples to glimmer-libui-dsl; at this point he is lightning speed ahead of
everyone else in regards to ruby + libui. :D

I regularly look through his examples to see what I can steal, I mean, borrow. :P

One example that caught my eye was this one here:

    examples/basic_table_color.rb

Image:

https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/master/images/glimmer-dsl-libui-linux-basic-table-color.png

The link to the ruby source code is here:

https://raw.githubusercontent.com/AndyObtiva/glimmer-dsl-libui/master/examples/basic_table_color.rb

(It's the raw ruby code, so it can be copy/pasted).

Andy evidently uses an array to colourize entries:

    data = [
      [['cat', :red]      , ['meow', :blue]                  , [true, 'mammal', :green], [img, 'Glimmer', :dark_blue], {r: 255, g: 120, b: 0, a: 0.5}],

So I suppose R G B stands for red green blue (I like that he used logical variables!)

I assume the :red, :blue and so forth are the colours. I actually use that in other ruby
projects myself - kind of neat to see DSLs being to some extend similar.

Andy then uses a higher level DSL for the actual code implementation:

    table {
      text_color_column('Animal')
      text_color_column('Sound')

Pretty epic.

Unfortunately I have absolutely no idea how Andy did this. I can not for the life of me figure out
upstream libui; the documentation is so sparse ... but evidently these things DO work. So I am having
a bit of a knowledge gap here.

So here comes my request:

- Would it be possible for ruby libUI here to add a simple example for ONE entry in a table?
Does not have to include any images or so; I just want to see how to colourize entries in a
table. For instance, first row light yellow, second row white background, third row light
yellow and so forth. Not sure if either of you two know how to do this in "raw" libui but it
would be great if libui itself could have such a simple example. (I also have to admit that
pointers and malloc are above my level of understanding ... I really should have learned C
properly before using ruby but ruby is so much more fun :P )

**Comment by kojix2** [comment]
@rubyFeedback

That was a more tedious task than I expected.
I added a red gradient background to the basic_table sample.

![image](https://user-images.githubusercontent.com/5798442/139566633-8cf38381-ae36-4ac8-af81-b33a818099dc.png)

Here, I added a third column to the table and set the background color.

```diff
diff --git a/examples/basic_table.rb b/examples/basic_table.rb
index 474e1d4..fa5d834 100644
--- a/examples/basic_table.rb
+++ b/examples/basic_table.rb
@@ -30,11 +30,17 @@ end
 
 model_handler = UI::FFI::TableModelHandler.malloc
 model_handler.to_ptr.free = Fiddle::RUBY_FREE
-model_handler.NumColumns   = rbcallback(4) { 2 }
-model_handler.ColumnType   = rbcallback(4) { 0 }
+model_handler.NumColumns   = rbcallback(4) { 3 }
+model_handler.ColumnType   = rbcallback(4, [1, 1, 4]) do |_, _, column|
+  column == 2 ? UI::TableValueTypeColor : UI::TableValueTypeString
+end
 model_handler.NumRows      = rbcallback(4) { 5 }
 model_handler.CellValue    = rbcallback(1, [1, 1, 4, 4]) do |_, _, row, column|
-  UI.new_table_value_string(data[row][column])
+  if column == 2
+    UI.new_table_value_color(1, 0, 0, row / 5.0)
+  else
+    UI.new_table_value_string(data[row][column])
+  end
 end
 model_handler.SetCellValue = rbcallback(0, [0]) {}
 
@@ -43,7 +49,7 @@ model = UI.new_table_model(model_handler)
 table_params = UI::FFI::TableParams.malloc
 table_params.to_ptr.free = Fiddle::RUBY_FREE
 table_params.Model = model
-table_params.RowBackgroundColorModelColumn = -1
+table_params.RowBackgroundColorModelColumn = 2
 
 table = UI.new_table(table_params)
 UI.table_append_text_column(table, 'Animal', 0, -1)
```

Full script.

```ruby
# frozen_string_literal: true

require 'libui'

UI = LibUI

UI.init

main_window = UI.new_window('Animal sounds', 300, 200, 1)

hbox = UI.new_horizontal_box
UI.window_set_child(main_window, hbox)

data = [
  %w[cat meow],
  %w[dog woof],
  %w[chicken cock-a-doodle-doo],
  %w[horse neigh],
  %w[cow moo]
]

# Protects BlockCaller objects from garbage collection.
@block_callers = []
def rbcallback(*args, &block)
  args << [0] if args.size == 1 # Argument types are ommited
  block_caller = Fiddle::Closure::BlockCaller.new(*args, &block)
  @block_callers << block_caller
  block_caller
end

model_handler = UI::FFI::TableModelHandler.malloc
model_handler.to_ptr.free = Fiddle::RUBY_FREE
model_handler.NumColumns  = rbcallback(4) { 3 }
model_handler.ColumnType  = rbcallback(4, [1, 1, 4]) do |_, _, column|
  column == 2 ? UI::TableValueTypeColor : UI::TableValueTypeString
end
model_handler.NumRows      = rbcallback(4) { 5 }
model_handler.CellValue    = rbcallback(1, [1, 1, 4, 4]) do |_, _, row, column|
  if column == 2
    UI.new_table_value_color(1, 0, 0, row / 5.0)
  else
    UI.new_table_value_string(data[row][column])
  end
end
model_handler.SetCellValue = rbcallback(0, [0]) {}

model = UI.new_table_model(model_handler)

table_params = UI::FFI::TableParams.malloc
table_params.to_ptr.free = Fiddle::RUBY_FREE
table_params.Model = model
table_params.RowBackgroundColorModelColumn = 2

table = UI.new_table(table_params)
UI.table_append_text_column(table, 'Animal', 0, -1)
UI.table_append_text_column(table, 'Description', 1, -1)

UI.box_append(hbox, table, 1)
UI.control_show(main_window)

UI.window_on_closing(main_window) do
  puts 'Bye Bye'
  UI.control_destroy(main_window)
  UI.free_table_model(model)
  UI.quit
  0
end

UI.main
UI.quit
```

If you want to change the text color instead of the background color, please see here.
https://github.com/AndyObtiva/glimmer-dsl-libui/blob/bc37abfb4134d8ab4e4ddc8f8fd78ce8eb147ce7/lib/glimmer/libui/control_proxy/column/text_color_column_proxy.rb#L42-L44
