### ISSUE TITLE
Turing Pattern

### ISSUE THREAD

**Issue by AndyObtiva** [kojix2/LibUI#41]
Hi,

Congrats on the new release! examples/draw_text.rb and examples/spectrum.rb worked nicely! 

The Turing Pattern example does work, but I do not see anything resembling waves with it. I made sure numo-narray gem is installed.

Here is a screenshot from Linux (starting didn't change anything):
![libui-linux-turing-pattern](https://user-images.githubusercontent.com/23052/143053943-b51fbaaa-3c45-4f02-9b20-197b86c289dc.png)

Here is a screenshot from Mac:
![Screen Shot 2021-11-23 at 10 38 02 AM](https://user-images.githubusercontent.com/23052/143055080-a3c01e09-4261-4e34-972a-9d01ae18da83.png)

Would you mind sharing a screenshot or more to demonstrate how the Turing Pattern example is supposed to look like when it is working well?

**Comment by kojix2** [comment]
Hi AndyObtiva!

Please click on some areas. Press Start.

![image](https://user-images.githubusercontent.com/5798442/143138678-74efbaab-02ec-4524-99eb-b1004bb99e47.png)

Then the pattern will start to appear.

![image](https://user-images.githubusercontent.com/5798442/143138796-d3a93e22-8cb7-4137-a5ce-6bb67cfe6d2d.png)

But LibUI is very slow, Gtk is much faster.
https://github.com/kojix2/gray_scott_gtk3

For the Turing pattern, there is a really nice work in Javascript
https://github.com/pmneila/jsexp

Thanks for looking at the release.

**Comment by AndyObtiva** [comment]
OK, thanks! I got it working.

![Screen Shot 2021-11-23 at 7 41 17 PM](https://user-images.githubusercontent.com/23052/143150881-b5baab98-f80d-458b-bd80-a440f90d00ba.png)

![Screen Shot 2021-11-23 at 7 42 20 PM](https://user-images.githubusercontent.com/23052/143150917-ad7f8f36-f366-4c78-a5e8-70ce2c66f5df.png)
