### ISSUE TITLE
libui-ng

### ISSUE THREAD

**Issue by kojix2** [kojix2/LibUI#46]
In future releases, we will consider including libui-ng in the package instead of the original libui.

https://github.com/andlabs/libui/issues/547
https://github.com/libui-ng/libui-ng

https://github.com/AndyObtiva/glimmer-dsl-libui/issues/17

**Comment by rubyFeedback** [comment]
This would be nice. There were some API changes already, from the changelog:

https://github.com/libui-ng/libui-ng/blob/master/CHANGELOG.md

Added

    uiBoxNumChildren() API
    uiFormNumChildren() API
    uiComboboxInsertAt() API
    uiComboboxDelete() API
    uiComboboxClear() API
    uiWindowResizeable() API
    uiWindowSetResizeable() API
    uiDrawPathEnded() API
    uiFreeFontDescriptor() API
    uiLoadControlFont() API

**Comment by kojix2** [comment]
Consider packing the static version in the gem instead of the shared version to prevent problems on Windows.
See https://github.com/kojix2/LibUI/issues/32#issuecomment-1023790045

**Comment by kojix2** [comment]
There is an undocumented environment variable called LIBUIDIR. You can use this environment variable to specify the path to the directory where the shared LibUI libraries are located.

```sh
git clone https://github.com/libui-ng/libui-ng
cd libui-ng
meson setup build
ninja -C build

cd build/meson-out
export LIBUIDIR=$(pwd)
```

**Comment by kojix2** [comment]
libui-ng provides Github Actions for build.
Each time a commit is pushed to the repository, libui-ng is automatically built and the artifacts are uploaded to the Actions page.

For example,
https://github.com/libui-ng/libui-ng/actions/runs/1801977866

**Comment by kojix2** [comment]
Added Rake task to build libui-ng

```
rake vendor:libui-ng
```

Confirmed to work on GithubActions macOS and Ubuntu.

**Comment by kojix2** [comment]
Added rake task to download [pre-build shared library for each platform](
https://nightly.link/kojix2/libui-ng/workflows/pre-build/pre-build).

```
rake vendor:kojix2:auto           # Download kojix2 pre-build for your platform to vendor directory
rake vendor:kojix2:mac            # Download kojix2 pre-build for Mac to vendor directory
rake vendor:kojix2:ubuntu_x64     # Download kojix2 pre-build for Ubuntu to vendor directory
rake vendor:kojix2:windows_x64    # Download kojix2 pre-build for Windows to vendor directory
rake vendor:kojix2:windows_x86    # Download kojix2 pre-build for Windows to vendor directory
```

I have released a preview version of the Gem.

- `gem build --platform x86_64-linux` did not work as expected. It needs to be improved.

**Comment by kojix2** [comment]
The workflow to download the original libui has been removed from the Rakefile. 
The project has been moved to libui-ng.
