### ISSUE TITLE
Exe wont start (Fiddle::DLError) Windows 11 Notebook 

### ISSUE THREAD

**Issue by Delikt** [kojix2/LibUI#48]
I build an Exe using ocra for my Application 

upgraded from Libui 0.0.12 to 0.0.13 (same issue)

I can start my Application without Problems on any Win 10 PC but on a single Windows 11 (upgraded Notebook from 10)  i got this Error:

```
C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/fiddle.rb:61:in `initialize': No such file or directory (Fiddle::DLError)
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/fiddle.rb:61:in `new'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/fiddle.rb:61:in `dlopen'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/fiddle/import.rb:86:in `block in dlload'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/fiddle/import.rb:77:in `collect'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/fiddle/import.rb:77:in `dlload'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/gems/3.0.0/gems/libui-0.0.12/lib/libui/ffi.rb:12:in `<module:FFI>'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/gems/3.0.0/gems/libui-0.0.12/lib/libui/ffi.rb:7:in `<module:LibUI>'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/gems/3.0.0/gems/libui-0.0.12/lib/libui/ffi.rb:6:in `<top (required)>'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/gems/3.0.0/gems/libui-0.0.12/lib/libui.rb:21:in `require_relative'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/gems/3.0.0/gems/libui-0.0.12/lib/libui.rb:21:in `<module:LibUI>'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/gems/3.0.0/gems/libui-0.0.12/lib/libui.rb:6:in `<top (required)>'
        from <internal:C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/gems/3.0.0/gems/glimmer-dsl-libui-0.2.23/lib/glimmer-dsl-libui.rb:33:in `<top (required)>'
        from <internal:C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/src/lucsi.rb:3:in `<main>'
<internal:C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- glimmer-dsl-libui (LoadError)
        from <internal:C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Users/Manuel/AppData/Local/Temp/ocr15B2.tmp/src/lucsi.rb:3:in `<main>'

```

I need to say on another Win 11 Notebook (Preinstalled) the Application run also without Problems.

Any Idea what i should do or check? Please tell me whatever further information you need, if you have a idea. Thanks

**Comment by kojix2** [comment]
Hi Delikt.
Thanks for the interesting report.

The most common cause of this error is that you are using a 32bit version of Ruby. This can be confirmed by typing `1.size == 8 # true if 64bit ruby` in irb.
https://github.com/kojix2/LibUI/issues/15

The second most common cause would be that Windows does not have some dependent library installed. We have not actually observed this situation and it is not completely understood, but it is believed to be the case.
https://github.com/kojix2/LibUI/issues/32

Finally, it is possible that the problem is due to differences in CPU architecture. It has been recently reported that LibUI does not work on Macs with newer CPUs.
https://github.com/kojix2/LibUI/issues/47

Nowadays it is rare to install 32-bit Ruby. If LibUI was running on the same computer before, I don't think the CPU is the cause. So I think it is the second case, but this is not fully understood.

**Comment by Delikt** [comment]
Thank you for your quick support kojix!

i tryed to evaluate the X.bit Version of my Ruby installation and i'm a bit confused cause:
![grafik](https://user-images.githubusercontent.com/22080674/150306622-659e24ea-c92d-4396-afb5-0d006e728892.png)

i have the x64 Version Installed of Ruby but 1.size == 8 => false

in case of the second possible Answere, i think i need to wait the progress of information Gathering 

for the third case: The upgraded Notebook (From Win10 to Win11) is an older CPU (6th generation Intel Core i5 - Model Inspiron 5759 from Dell). I tested it on modern PC's with Intel i5 from 8 to 10th Generation without Problems.

**Comment by kojix2** [comment]
It's strange that `1.size` is not 8. Please tell me the result of `1.size` ?

> Document-method: Integer#size
> Returns the number of bytes in the machine representation of int (machine depende
https://docs.ruby-lang.org/en/3.1/Integer.html#method-i-size

**Comment by Delikt** [comment]
1.size is 4 

so its a 32bit irb Console? O.o

**Comment by Delikt** [comment]
Ok, again on another Win10 PC i got this Error - i tryed to build the exe with ocra incl. the Parameter  "--debug-extract" to check if something missing on the PC's where i get the Error but:

![grafik](https://user-images.githubusercontent.com/22080674/150794365-60849586-7a47-471b-a321-6998b20d2166.png)

**Comment by Delikt** [comment]
I checked the depending dlls for LibUI located in Windows\System32 Folder on the Win 11 Notebook, all Dependencys are there


List of Dependencys from Issue #32:

```
$ objdump -p vendor/libui.dll | grep -i dll
vendor/libui.dll:     ファイル形式 pei-x86-64
    DLL
DllCharacteristics    00000160
 vma:            Hint    Time      Forward  DLL       First
    DLL Name: USER32.dll
    DLL Name: KERNEL32.dll
    DLL Name: GDI32.dll
    DLL Name: UxTheme.dll
    DLL Name: d2d1.dll
    DLL Name: DWrite.dll
    DLL Name: ole32.dll
    DLL Name: MSVCP140.dll
    DLL Name: VCRUNTIME140.dll
    DLL Name: api-ms-win-crt-math-l1-1-0.dll
    DLL Name: api-ms-win-crt-runtime-l1-1-0.dll
    40142       63  _seh_filter_dll
    DLL Name: api-ms-win-crt-convert-l1-1-0.dll
    DLL Name: api-ms-win-crt-stdio-l1-1-0.dll
    DLL Name: api-ms-win-crt-string-l1-1-0.dll
    DLL Name: api-ms-win-crt-utility-l1-1-0.dll
    DLL Name: api-ms-win-crt-heap-l1-1-0.dll
名前                 000000000003ca0e libui.dll
```

**Comment by Delikt** [comment]
i also tryed to install Net Framework 3.5 Sp1 like https://github.com/kojix2/LibUI/issues/32#issuecomment-986315897  wrote as hint on the Win 11 Notebook. But this didnt Changed anything - same Error.

**Comment by kojix2** [comment]
Thanks @Delikt 

For the first case, I think that the 32bit Ruby installed before is still there and it is running. However, the screenshot does indeed look like a 64-bit version of Ruby. However, I don't know much about Windows at all, so there might be a case that `1.size` becomes 4 even if you have a 64bit version of Ruby. In that case, please let me know again.

For the latter case, could you please check if the official LibUI release works?

Download the following two files from [here](https://github.com/andlabs/libui/releases/tag/alpha4.1)

* examples-alpha4.1-windows-amd64-shared.zip
* libui-alpha4.1-windows-amd64-shared.zip

Unzip the file, copy `libui.dll` to the example directory,

![image](https://user-images.githubusercontent.com/5798442/150874681-3865c74b-ad64-41cb-848b-3704a1e4ea99.png)

And start controlgallery.exe.

![image](https://user-images.githubusercontent.com/5798442/150875016-b2bfdbda-cd6b-4220-993d-b7464bfc086c.png)

If this does not work, it means that Ruby's LibUI also does not work because it calls `libui.dll`.

**Comment by Delikt** [comment]
i got 2 Errors on the not working Win 11 Notebook:

in short: "Can't execute the Code, MSVCP140.ddl and VCRUNTIME140.dll not found

![grafik](https://user-images.githubusercontent.com/22080674/150929845-2fc82e1e-0eef-4f09-a312-2588634f5343.png)

![grafik](https://user-images.githubusercontent.com/22080674/150929862-fa49856d-edd4-4e95-b353-d9b6124a7970.png)

On a PC without start Problems, these Example.exe works fine

**Comment by Delikt** [comment]
On a PC where my Application works are many more MSVCP140.dll's and VCRUNTIME140.dll's in the system32 Subdirectorys:

![grafik](https://user-images.githubusercontent.com/22080674/150943483-25623f34-495b-4be9-a6b7-d71bb198098b.png)

![grafik](https://user-images.githubusercontent.com/22080674/150943583-665446f9-48f6-43a1-aed6-d24d0e1125b2.png)

**Comment by kou** [comment]
`vcruntime140.dll` and `msvcp140.dll` don't exist in `c:\Windows\system32` on the problem PC.
(They exist in "sub folders" in `c:\Windows\system32`.)

Could you try installing "Microsoft Visual C++ 2015 Redistributable Update 3" from https://visualstudio.microsoft.com/vs/older-downloads/ on the problem PC.
(You need to expand "Other Tools, Frameworks, and Redistributables".)

**Comment by Delikt** [comment]
IT WORK! 

For the example.exe it was just necessary to copy the missing dll's in the same Folder where the example.exe is located:

![grafik](https://user-images.githubusercontent.com/22080674/151137270-66b8553b-feae-434c-ac01-dcd9bed5e439.png)

But for my Application this was not the solution - i got the same Error

To install "Microsoft Visual C++ 2015 Redistributable Update 3"  was also not the solution but almost.

**I installed the newest Version of the MS Redistributable Package (2015-2022) 
https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

https://aka.ms/vs/17/release/vc_redist.x64.exe**

and after that my App starting and work!

Thank you very much kojix2 and kou !

**Comment by kojix2** [comment]
As always, thank you very much, @kou.

I have heard before that it is difficult for Fiddle to detect a missing DLL.
Even if Fiddle can't raise an exception, it would be nice if Windows could raise some kind of error message!
