### ISSUE TITLE
Glimmer DSL for LibUI Wins Fukuoka Ruby 2022 Special Award

### ISSUE THREAD

**Issue by AndyObtiva** [kojix2/LibUI#49]
https://andymaleh.blogspot.com/2022/02/glimmer-dsl-for-libui-wins-fukuoka-ruby.html

http://www.digitalfukuoka.jp/topics/187?locale=ja

This is just a celebratory issue and a big thanks to @kojix2 for contributing to the win of Glimmer DSL for LibUI at the 2022 Fukuoka Ruby Award Competition!

Take this as a great encouragement that the C libui and LibUI Ruby bindings have won indirectly too after Glimmer DSL for LibUI has been presented to and reviewed by Matz, the creator of Ruby, at the 2022 Fukuoka Ruby Award Competition!

I hid from you before the fact that Glimmer DSL for LibUI got selected as a finalist in Fukuoka Ruby Award Competition 2022 because I wanted to receive the final results first, which just came back!

Cheers and keep LibUI alive and greatly useful!!!

CC @rubyFeedback

**Comment by kojix2** [comment]
Wow!
I was surprised 😲 😊
