### ISSUE TITLE
libui-ng - "beta" ffi for it, for "early testing"?

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/LibUI#50]
Hey there kojix2,

I saw your activity/issue tracker in regards to libui-ng.

cody271 wrote about libui-ng needing more time before a
"milestone release" (or however he calls the first 
major release of libui-ng, which as far as I understand
has not yet been released).

I would, however had, already like to test libui on 
linux specifically, via ruby, if that is possible. This
of course needs the ffi-specific code you wrote already
(for andlabs libui), and I assume this is not yet adjusted
to libui-ng, since the libui-ng code has some changes
listed in the CHANGELOG file.

As far as I understand the ffi-specific code for the ffi-specific
libui code you wrote is stored here:

    https://github.com/kojix2/LibUI/blob/main/lib/libui/ffi.rb

So, my first thought is ... what if a second .rb file
is added there, in the same directory, that specifically
deals with the changes of libui-ng only? That is, a single
new .rb file that focuses only on the changes that were
made in libui-ng.

My basic thinking here is the following:

- People can still use the current ffi.rb for main libui
(from andlabs) as-is.

- At the same time, they can also "opt-in" to use that
second .rb file (which has not yet been created) that
specifically caters towards the libui-ng specific
changes.

Then they could perhaps selectively use what they want
to, the original libui, the libui-ng variant or both.

I am not sure if this is too much work, so please take
this only as a rough idea. I know too little about C
and ffi to really understand how it works, so my 
thinking may be off here.

I would love to test the changes that cody271 did,
e. g. these ones in particular:

    https://raw.githubusercontent.com/libui-ng/libui-ng/master/CHANGELOG.md

Last but not least, I saw you are asking or perhaps
looking for support in maintaining libui. If you 
would like to you could add me on github (I think
this is possible via the web-interface; I remember
kou did so for ruby-gnome in the past) and as a
co-maintainer on rubygems.org. My handle on rubygems
is "shevy"; https://rubygems.org/profiles/shevy

The reason I use another nick on github is mostly
because I use primarily rubygems for distributing
code; and github primarily for feedback-related 
issues only. (I used git in the past, but I found
it does not align well with my workflow. I am 
using mostly ruby scripts for my workflow, e. g.
on rubygems pushing new releases is so much easier
for me via my self-written scripts.)

In regards to trying to help maintain projects: 
unfortunately I do not know C, so I can never
really maintain libui as a whole. But I can try
to polish things every now and then if possible
(and wanted).

Perhaps you can also add Andy - I have not asked
him, but he possibly may not mind. Little changes
can probably be easy to do, for instance, documentation
or examples. (For example, if the new changes in
libui-ng are done, I'd love to add examples, so 
if I can figure out how these work I could add 
them to libui too.)

Anyway, the TL;DR summary for the issue request here is:

- Can it be considered to add support via a new .rb file for the libui-ng
specific parts, even if only for linux, as an "early testing" variant?
(It's fine for me to have this all work better at a later time on windows;
for now I really just want to test out stuff and see how this may eventually
work on windows too. On linux I tend to use ruby-gtk3 anyway, but I'd
love to polish libui on windows as much as that is possible too. And
early testing may be helpful in this regard)

**Comment by rubyFeedback** [comment]
(And if it is a beta release then just have the code on github, without yet making a new .gem release
and advertise this. That way people can test as-is without having to wait, but it is not yet "official"
for libui to endorse people use it. So this is really an early test/dev idea really. I don't mean this
for everyone to use right now.)

**Comment by kojix2** [comment]
I'd like to add you as a collaborator, but your nickname @rubyFeedback sounds strange to me.
Maybe you have another Github account not only for feedback, but also for committing code?
Anyway, I will send you an email requesting a collaborator. Please approve it.

**Comment by AndyObtiva** [comment]
Hi @kojix2 

Could you please add me as a collaborator too? I'd be happy to maintain your repo if you ever need to step out for other priorities in your life.

**Comment by rubyFeedback** [comment]
Thank you for the invite kojix2!

I will try to help when possible - as I don't know C (even though it's on my todo list
to learn) I will try to focus on polishing and improving smaller things when possible,
such as typos, documentation, perhaps examples.

I will close this issue here in ~2 weeks if nobody objects, to help clean the bug
tracker clean (I did not want to close it while Andy has the above request in
place).

**Comment by kojix2** [comment]
> Hi @kojix2
> 
> Could you please add me as a collaborator too?

Sure!
