### ISSUE TITLE
libui-ng related methods: how to use it?

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/LibUI#59]
Hey there kojix2,

I saw the changelog - for instance in ffi.rb:

    try_extern 'void uiComboboxClear(uiCombobox *c)'

So I was thinking I could use .clear() on a combobox. But when I tested in irb,
the method name was not showing up (or perhaps I made a mistake).

IF it is possible to clear a combo box, could a simple example be added that
shows how this could be done? Or perhaps what the name of the method
may be.

I tried via irb but I could only see these methods:

    LibUI.combobox_append 
    LibUI.combobox_on_selected
    LibUI.combobox_selected    
    LibUI.combobox_set_selected

Does one have to do something special to tap into that ffi.rb related functionality?

**Comment by kojix2** [comment]
I have not yet prepared an easy way to use libui-ng with Ruby's LibUI.
Still, it is great that you want to try libui-ng.

I just tried to see if I could reproduce the problem, but I could not. ( ui_combobox_clear showed up in irb )

Perhaps you are using the latest RubyGem? Or are you using andlabs branch?
If that is the case, the libui-ng methods will not show up. You need to use the main branch on Github.

I wrote previously that I wanted to use libui-ng in 0.0.15, but it did not happen and 0.0.15 simply supports M1 Mac. Sorry if this caused any confusion.

As you may already know, here is the link again on how to specify libui.so using the LIBUIDIR environment variable. if you use libui-ng, you must specify the location of libui.so yourself. (Alternatively, you can copy it into the vendor directory.)

https://github.com/kojix2/LibUI/issues/46
