### ISSUE TITLE
Organising on https://github.com/kojix2 ?

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/LibUI#61]
Hey there kojix2,

Sorry for misusing the issue tracker here. This is not specific to LibUI, but instead I have a question or
suggestion for your website/homepage at the least on github: https://github.com/kojix2

You have a lot of different projects, including (if I understood it correctly) various bioinformatics-related
projects, as well as several in crystal. I actually started to learn crystal but I am slow, so ... who knows
when I'll understand crystal better. :D

Anyway.

Some time ago I started to be more serious about one of my own bioinformatics-related project, and
while my TODO list is huge there, I also decided that I want to be able to generate graphics - ideally
even interactive via a GUI, but also in a way to allow one to generate graphics and plots and charts
that can be published in a scientific paper (ideally), without the end user needing to know everything
about HOW these graphs are generated. I want to simplify this.

I looked at various options, gnuplot and so forth, but right now I have settled for ImageMagick +
RMagick, simply because I seem to be able to more easily do what I think I want to do. But there
is also GR and I think you are one of those who maintain GR. I have only recently started to look
at it, already generated some charts with it (as .png files) and that works well.

Ok - so this was just the lengthy introduction to the issue here, so let me get back to what I mean.

If you look at your homepage on github at https://github.com/kojix2 it seems as if you have 159
repositories, probably some are inactive, some are just clones of other repositories so probably
not all of these were started by you. But it's still quite a lot, and I am not even sure how many
bioinformatics-specific libraries or applications you have or maintain there. I have a peek look
every now and then, but I get distracted by tons of things on the internet, so my attention span
is shorter than a squirrel on a sugar-nut rush.

If you ever have some time on some weekend in the future, do you think you could re-organise
the main webpage a little bit more? I can't say how, but just so that on a first visit to your homepage
there, we could more readily see which projects seem more important? I noticed you did something
similar in regards to bio-ruby specific gems. Perhaps you could do something like this for your
homepage too, e. g. something like:

Project 1: "this is about cats" -> Link
Project 2: "this is about dogs" -> Link
Project 3: "this is about ninja" -> Link

And so forth. Just so that a visitor can get a better overview with a little bit of context.

You kind of already do so, e. g. via "Plotting / Data" or "Bioinformatics", but I am not sure
which of these projects are more relevant or more important. I'd love to integrate some of
the projects you created/maintain (such as https://github.com/ruby-on-bioc/bio-bigwig)
but I don't quite know which ones are more important or more relevant, and I kind of have
to understand them first a little bit better before I can add code to support something (as
otherwise my code will be broken or bad, and then others can't really use broken code
if I don't understand the problem domain at hand well enough.)

Anyway, sorry for the issue, please feel free to ignore/close/disregard as it fits.

PS: By the way, as you have both GR.rb and GR.cr it would be interesting to compare
similar tasks there, e. g. 3 samples each doing the same, and how it looks in ruby and
how it looks in crystal. I assume the crystal variant will be slightly longer because 
crystal requiring type information sometimes, but it may be interesting to see 
advantages and disadvantages. Perhaps larger and more complicated plots take
longer in ruby.

**Comment by kojix2** [comment]
Hey, Post it here :point_down: 
https://github.com/kojix2/kojix2

**Comment by kojix2** [comment]
But here are a few questions to answer.

(1) My Crystal is almost entirely Ruby itself. Crystal has all sorts of useful features. But I don't know them.
(2) If you want to make academic charts, I recommend the R language; the ecosystem that Hadley Wickham and his colleagues have created is incredible. Looking back on it from the future it will feel like OOPArts. People say Python is amazing, but in my opinion, Python is not particularly interesting, except for the amazing number of people building libraries, and R is much more interesting. Maybe I think so because I know Ruby.
(3) I maintain only the projects listed at github.com/kojix2/kojix2. I created kojix2/kojix2 because I cannot remember which projects I have to maintain myself. You don't need to look at any other repositories unless you have a special reason to do so.

**Comment by kojix2** [comment]
@rubyFeedback 
If you are serious about exchanging ideas on bioinformatics, you may need to disclose your affiliation and communicate with me under your real name. In that case, please contact me by e-mail.
However, I prefer to remain anonymous and I assume you prefer to remain anonymous as well. If you have no particular need to do so, please remain anonymous.
