### ISSUE TITLE
Two duplicate lines, I think, at: https://github.com/kojix2/LibUI/blob/main/examples/draw_text.rb#L92

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/LibUI#74]
I recently went through the examples, trying to polish them, and I 
think there is a duplicate line or actually two here:

https://github.com/kojix2/LibUI/blob/main/examples/draw_text.rb#L92

**Comment by kojix2** [comment]
You finally committed code to the repository using git.
Glad to see your great step!

**Comment by rubyFeedback** [comment]
\o/

Now if only I would understand C ... :)

(It's on my perpetual todo list ... but first I have to improve Java - there are many
opportunities via Java too; Andy showed that via glimmer-SWT, and there is
truffleruby in graalvm, as well as jruby. C and C++ are kind of the "real deal"
though, even ruby is written in C.)

**Comment by kojix2** [comment]
If you are interested in using C from Ruby, it is not difficult.

1. Prepare the shared library.
2. Check the library's [header file](https://github.com/libui-ng/libui-ng/blob/master/ui.h) and remember the signature of the function you want to call.
3. Use gems like [FFI](https://github.com/ffi/ffi/wiki) or [Fiddle](https://github.com/ruby/fiddle) to define the [FFI module](https://github.com/kojix2/LibUI/blob/main/lib/libui/ffi.rb). 
    1. [Specify the path](https://github.com/kojix2/LibUI/blob/74934febc9542d157366c74a34e0ae909a25f661/lib/libui/ffi.rb#L10) to the shared library.
    2. [Define the method](https://github.com/kojix2/LibUI/blob/74934febc9542d157366c74a34e0ae909a25f661/lib/libui/ffi.rb#L38-L645) in the module using `attach_function` or `extern`.

With these steps, the module will be able to call C functions.
