### ISSUE TITLE
Request for the addition of a new example: an example in how to use LibUI.new_scrolling_area

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/LibUI#82]
Hey there kojix2,

I am trying to write a meta-GUI project right now, where
I want to use e. g.:

    button {
    }

And it should work for gtk2, gtk3, gtk4, wxwidgets, the
world wide web (e. g. in a sinatra or rails or cgi 
environment) and so forth - and of course libui.

The C code, as far as I can see it, looks like this:

    static void handlerDraw(uiAreaHandler *a, uiArea *area, uiAreaDrawParams *p)

So three arguments have to be passed to this function. I don't quite know
how to use that though. My goal is to have a scrolled-window
work, similar to ruby-gtk3.

If you understand the code, can you add a SIMPLE example 
that is just a text-view basically, but has scrolled
panes on the side, e. g. how this works with
LibUI.new_scrolling_area?

I'll keep on googling but right now I simply don't know
how to use LibUI.new_scrolling_area and I could not find
an example in ruby-libui here, so perhaps this could be
added when you have time and feel motivated to do so.

**Comment by rubyFeedback** [comment]
Hmm looks as if this is not possible. Not sure what the purpose
of LibUI.new_scrolling_area is, but if it is not possible then this
is not a relevant request from me as it can not be supported
right now.

See: https://github.com/andlabs/libui/issues/178

**Comment by AndyObtiva** [comment]
Glimmer DSL for LibUI includes an example for scrolling area. 

https://github.com/AndyObtiva/glimmer-dsl-libui/blob/master/docs/examples/GLIMMER-DSL-LIBUI-BASIC-EXAMPLES.md#basic-scrolling-area

![IMG_0632](https://github.com/kojix2/LibUI/assets/23052/fd580846-aef4-4bca-858f-7349d703f18b)

![IMG_4597](https://github.com/kojix2/LibUI/assets/23052/bdcb6853-e0f1-4d0d-96f9-5b3c603c4d2d)

Code:

https://github.com/AndyObtiva/glimmer-dsl-libui/blob/master/examples/basic_scrolling_area.rb

You can dig into the Glimmer DSL for LibUI implementation to learn more about how it is used from LibUI.
